spring.application.name=pro2_sm_2

# veritaban? ad?n buradaki ile ayn? olsun. ---> school_db
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db 
spring.datasource.username=postgres
spring.datasource.password=ilikesql
spring.datasource.driver-class-name=org.postgresql.Driver




spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


